#!/usr/bin/env python3
"""
Housekeeping for catalogue.sqlite: migrations, the checked-in schema, and the checked-in data dump.

    python3 catalogue_db.py migrate         # apply pending migrations/*.sql to catalogue.sqlite
    python3 catalogue_db.py schema          # regenerate schema.sql from migrations/ (no DB needed)
    python3 catalogue_db.py schema --check  # exit 1 if schema.sql is out of date
    python3 catalogue_db.py dump            # catalogue.sqlite -> catalogue/ (the canonical, committed form)
    python3 catalogue_db.py dump --check    # exit 1 if catalogue/ does not match catalogue.sqlite
    python3 catalogue_db.py build [--force] # catalogue/ -> catalogue.sqlite (the .sqlite file is git-ignored)
    python3 catalogue_db.py build --check   # rebuild into a temp file and verify it dumps back identically

schema.sql is generated, never edited: it is every migration applied to an empty database, printed
in creation order. Change the schema by adding a migration, then regenerate.

The dump (Q9) is data only, one file per table: catalogue/<table>.sql with one INSERT per row, ordered by
primary key, so diffs show exactly the rows that changed. help_pages (raw HTML, ~95% of the bytes, and
append-only) gets one file per fetched page under catalogue/help_pages/, so a refresh adds files instead
of growing one huge file. catalogue/_migrations.txt lists the migrations the data was dumped under; `build`
applies exactly those, loads the data, then applies any newer migrations. .gitattributes marks
catalogue/ as -text: git must not convert line endings inside stored text.

Standard library only. On Windows: `uv run --no-project catalogue_db.py ...`.
"""

import argparse
import contextlib
import io
import re
import sqlite3
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import scrape_help
from scrape_help import BASE_DIR

SCHEMA_PATH = BASE_DIR / "schema.sql"
DB_PATH = scrape_help.DB_PATH
DUMP_DIR = BASE_DIR / "catalogue"
MIGRATIONS_FILE = "_migrations.txt"
NOT_DUMPED = {"schema_migrations"}   # its names go to _migrations.txt; applied_at is volatile
PER_ROW = {"help_pages"}             # one file per row: catalogue/<table>/<id>-<slug>.sql
HEADER = (
    "-- GENERATED by `catalogue_db.py schema` from migrations/*.sql. Do not edit; add a migration instead.\n"
    "-- The catalogue schema after all migrations, in creation order.\n"
)


def render_schema():
    conn = sqlite3.connect(":memory:")
    with contextlib.redirect_stdout(io.StringIO()):  # apply_migrations prints one line per migration
        scrape_help.apply_migrations(conn)
    migrations = [r[0] for r in conn.execute("SELECT name FROM schema_migrations ORDER BY name")]
    # ALTER TABLE rewrites a table's stored SQL in place, so creation order still holds.
    rows = conn.execute(
        "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    ).fetchall()
    conn.close()
    out = [HEADER, "-- Migrations: " + ", ".join(migrations) + "\n"]
    for (sql,) in rows:
        out.append("\n" + sql.strip() + ";\n")
    return "".join(out)


def cmd_schema(args):
    text = render_schema()
    current = SCHEMA_PATH.read_text(encoding="utf8") if SCHEMA_PATH.exists() else None
    if args.check:
        if current != text:
            print("schema.sql is out of date: run `catalogue_db.py schema`", file=sys.stderr)
            return 1
        print("schema.sql is up to date")
        return 0
    if current == text:
        print("schema.sql unchanged")
    else:
        SCHEMA_PATH.write_text(text, encoding="utf8", newline="\n")
        print(f"wrote {SCHEMA_PATH.name}")
    return 0


# ── dump / build ─────────────────────────────────────────────────────────────

def sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, bytes):
        return "X'" + value.hex().upper() + "'"
    return "'" + value.replace("'", "''") + "'"


def dumped_tables(conn):
    return [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
        if r[0] not in NOT_DUMPED]


def order_by(conn, table):
    pk = sorted((r[5], r[1]) for r in conn.execute(f'PRAGMA table_info("{table}")') if r[5])
    return ", ".join(f'"{name}"' for _, name in pk) if pk else "rowid"


def row_file_name(table, row):
    """help_pages/0123-commit-transaction.sql: id first (stable, append-only), slug for humans."""
    slug = re.sub(r"[^a-z0-9-]+", "-", row["url"].rsplit("/", 1)[-1].removesuffix(".html").lower()).strip("-")
    return f"{table}/{row['id']:04d}-{slug}.sql"


def render_dump(conn):
    """{relative path: bytes} for the whole database."""
    conn.row_factory = sqlite3.Row
    files = {}
    migrations = [r[0] for r in conn.execute("SELECT name FROM schema_migrations ORDER BY name")]
    files[MIGRATIONS_FILE] = "".join(m + "\n" for m in migrations)
    for table in dumped_tables(conn):
        cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{table}")')]
        head = f'INSERT INTO "{table}" (' + ", ".join(f'"{c}"' for c in cols) + ") VALUES ("
        rows = conn.execute(f'SELECT * FROM "{table}" ORDER BY {order_by(conn, table)}')
        if table in PER_ROW:
            for row in rows:
                files[row_file_name(table, row)] = head + ", ".join(sql_literal(v) for v in row) + ");\n"
        else:
            lines = [f"-- {table}: generated by `catalogue_db.py dump`; change the database, not this file.\n"]
            lines += [head + ", ".join(sql_literal(v) for v in row) + ");\n" for row in rows]
            files[f"{table}.sql"] = "".join(lines)
    conn.row_factory = None
    return {k: v.encode("utf8") for k, v in files.items()}


def read_dump(directory):
    if not directory.exists():
        return {}
    return {p.relative_to(directory).as_posix(): p.read_bytes()
            for p in directory.rglob("*") if p.is_file() and (p.suffix == ".sql" or p.name == MIGRATIONS_FILE)}


def diff_dump(wanted, current):
    changed = sorted(k for k in wanted if current.get(k) != wanted[k])
    stale = sorted(set(current) - set(wanted))
    return changed, stale


def cmd_dump(args):
    if not DB_PATH.exists():
        print(f"{DB_PATH.name} not found; run `build` first", file=sys.stderr)
        return 1
    conn = sqlite3.connect(DB_PATH)
    pending = {p.name for p in scrape_help.MIGRATIONS_DIR.glob("*.sql")} - {
        r[0] for r in conn.execute("SELECT name FROM schema_migrations")}
    if pending:
        print(f"unapplied migrations {sorted(pending)}: run `migrate` first", file=sys.stderr)
        return 1
    files = render_dump(conn)
    conn.close()
    changed, stale = diff_dump(files, read_dump(DUMP_DIR))
    if args.check:
        if changed or stale:
            print(f"catalogue/ is out of date ({len(changed)} changed, {len(stale)} stale): run `dump`",
                  file=sys.stderr)
            for k in (changed + stale)[:20]:
                print(f"  {k}", file=sys.stderr)
            return 1
        print(f"catalogue/ matches {DB_PATH.name} ({len(files)} files)")
        return 0
    for k in changed:
        path = DUMP_DIR / k
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(files[k])
    for k in stale:
        (DUMP_DIR / k).unlink()
    print(f"dumped {len(files)} files: {len(changed)} written, {len(stale)} removed")
    return 0


def load_statements(conn, sql):
    """Run each statement of a dump file inside the open transaction (executescript would commit it)."""
    parts = []
    for line in sql.splitlines(keepends=True):
        parts.append(line)
        # Every dumped statement ends with ");" at a line end; only test there (pages are ~1000 lines).
        if line.rstrip("\r\n").endswith(");"):
            stmt = "".join(parts)
            if sqlite3.complete_statement(stmt):
                conn.execute(stmt)
                parts = []
    stmt = "".join(parts)
    if stmt.strip() and not all(ln.lstrip().startswith("--") or not ln.strip() for ln in stmt.splitlines()):
        raise SystemExit(f"incomplete statement at the end of a dump file: {stmt[:80]!r}")


def build_into(path):
    """Create a database at path from catalogue/; returns the newer migrations applied after loading."""
    dump = read_dump(DUMP_DIR)
    if MIGRATIONS_FILE not in dump:
        raise SystemExit(f"catalogue/{MIGRATIONS_FILE} not found; nothing to build from")
    dumped_under = dump.pop(MIGRATIONS_FILE).decode("utf8").split()
    conn = sqlite3.connect(path, isolation_level=None)
    conn.execute("CREATE TABLE schema_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)")
    built_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for name in dumped_under:
        migration = scrape_help.MIGRATIONS_DIR / name
        if not migration.exists():
            raise SystemExit(f"the dump needs migrations/{name}, which does not exist")
        conn.executescript(migration.read_text(encoding="utf8"))
        conn.execute("INSERT INTO schema_migrations VALUES (?, ?)", (name, built_at))
    tables = set(dumped_tables(conn))
    conn.execute("PRAGMA foreign_keys = OFF")  # tables load in name order, not dependency order
    conn.execute("BEGIN")
    for rel in sorted(dump):
        table = rel.split("/")[0].removesuffix(".sql")
        if table not in tables:
            raise SystemExit(f"catalogue/{rel}: no table {table} after {dumped_under[-1]}")
        load_statements(conn, dump[rel].decode("utf8"))
    conn.execute("COMMIT")
    problems = conn.execute("PRAGMA foreign_key_check").fetchall()
    if problems:
        raise SystemExit(f"foreign key problems after loading: {problems[:5]}")
    before = {r[0] for r in conn.execute("SELECT name FROM schema_migrations")}
    with contextlib.redirect_stdout(io.StringIO()):
        scrape_help.apply_migrations(conn)
    newer = sorted({r[0] for r in conn.execute("SELECT name FROM schema_migrations")} - before)
    conn.close()
    return newer


def cmd_build(args):
    if args.check:
        # Round trip: catalogue/ -> temp database -> dump must give back catalogue/ byte for byte.
        with tempfile.TemporaryDirectory() as tmp:
            db = Path(tmp) / "roundtrip.sqlite"
            newer = build_into(db)
            conn = sqlite3.connect(db)
            changed, stale = diff_dump(render_dump(conn), read_dump(DUMP_DIR))
            conn.close()
        if newer:
            print(f"note: newer migrations applied after loading: {', '.join(newer)}")
        if changed or stale:
            print(f"round trip differs ({len(changed)} changed, {len(stale)} missing): {(changed + stale)[:10]}",
                  file=sys.stderr)
            return 1
        print("round trip ok: catalogue/ builds a database that dumps back identically")
        return 0
    if DB_PATH.exists() and not args.force:
        print(f"{DB_PATH.name} exists; pass --force to replace it (the old file is kept as .bak)", file=sys.stderr)
        return 1
    tmp = DB_PATH.with_suffix(".sqlite.tmp")
    tmp.unlink(missing_ok=True)
    newer = build_into(tmp)
    # Copy pages with SQLite's backup API instead of renaming files: on Windows a file that PHPStorm
    # (or any reader) has open cannot be renamed, but it can be rewritten through SQLite's locking.
    source = sqlite3.connect(tmp)
    if DB_PATH.exists():
        current = sqlite3.connect(DB_PATH)
        bak = sqlite3.connect(DB_PATH.with_suffix(".sqlite.bak"))
        current.backup(bak)
        bak.close()
        source.backup(current)
        current.close()
    else:
        target = sqlite3.connect(DB_PATH)
        source.backup(target)
        target.close()
    source.close()
    tmp.unlink()
    print(f"built {DB_PATH.name} from catalogue/" + (f"; then applied {', '.join(newer)}" if newer else ""))
    if newer:
        print("run `dump` so catalogue/ records the migrated data")
    return 0


def cmd_migrate(args):
    conn = scrape_help.connect()  # applies pending migrations
    conn.close()
    print("catalogue.sqlite is up to date")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("migrate").set_defaults(func=cmd_migrate)
    schema = sub.add_parser("schema")
    schema.add_argument("--check", action="store_true", help="fail if schema.sql differs from the migrations")
    schema.set_defaults(func=cmd_schema)
    dump = sub.add_parser("dump")
    dump.add_argument("--check", action="store_true", help="fail if catalogue/ differs from catalogue.sqlite")
    dump.set_defaults(func=cmd_dump)
    build = sub.add_parser("build")
    build.add_argument("--force", action="store_true", help="replace an existing catalogue.sqlite")
    build.add_argument("--check", action="store_true", help="verify catalogue/ round-trips, touching nothing")
    build.set_defaults(func=cmd_build)
    args = parser.parse_args()
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
