-- GENERATED by `catalogue_db.py schema` from migrations/*.sql. Do not edit; add a migration instead.
-- The catalogue schema after all migrations, in creation order.
-- Migrations: 0001_help_catalogue.sql, 0002_calc_catalogue.sql, 0003_representations.sql, 0004_step_option_origin.sql

CREATE TABLE schema_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL);

CREATE TABLE fm_versions (
    id             INTEGER PRIMARY KEY,
    version        TEXT NOT NULL UNIQUE,            -- '19.6.1'
    major          INTEGER NOT NULL,
    minor          INTEGER NOT NULL,
    patch          INTEGER NOT NULL,
    marketing_name TEXT,
    released_on    TEXT,
    sort_key       INTEGER NOT NULL                 -- major*1000000 + minor*1000 + patch
);

CREATE INDEX idx_fm_versions_sort_key ON fm_versions (sort_key);

CREATE TABLE help_pages (
    id               INTEGER PRIMARY KEY,
    url              TEXT NOT NULL,
    locale           TEXT NOT NULL,
    kind             TEXT NOT NULL,                 -- 'reference' | 'category' | 'step'
    fetched_at       TEXT NOT NULL,                 -- ISO 8601 UTC
    http_status      INTEGER NOT NULL,
    page_modified_at TEXT,                          -- <meta property="article:modified_time">
    raw_html         TEXT NOT NULL,
    sha256           TEXT NOT NULL,                 -- of raw_html
    UNIQUE (url, fetched_at)
);

CREATE INDEX idx_help_pages_url ON help_pages (url);

CREATE TABLE script_step_categories (
    id       INTEGER PRIMARY KEY,
    slug     TEXT NOT NULL UNIQUE,                  -- 'control', 'found-sets', 'pdf-files'
    position INTEGER NOT NULL                       -- order on the help site
);

CREATE TABLE script_step_category_localizations (
    category_id  INTEGER NOT NULL REFERENCES script_step_categories (id),
    locale       TEXT NOT NULL,
    name         TEXT NOT NULL,                     -- 'Control script steps'
    description  TEXT,
    help_page_id INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (category_id, locale)
);

CREATE TABLE script_steps (
    id                       INTEGER PRIMARY KEY,
    slug                     TEXT NOT NULL UNIQUE,  -- 'commit-transaction' (help URL basename)
    fm_step_id               INTEGER UNIQUE,        -- NULL until the XML importer matches it up
    category_id              INTEGER REFERENCES script_step_categories (id),
    originated_in_version_id INTEGER REFERENCES fm_versions (id),
    originated_in_raw        TEXT,                  -- help text verbatim, kept when it will not parse
    deprecated_in_version_id INTEGER REFERENCES fm_versions (id),
    removed_in_version_id    INTEGER REFERENCES fm_versions (id)
, control_flow_role TEXT, is_container_step INTEGER NOT NULL DEFAULT 0, is_terminator_step INTEGER NOT NULL DEFAULT 0);

CREATE TABLE script_step_localizations (
    script_step_id INTEGER NOT NULL REFERENCES script_steps (id),
    locale         TEXT NOT NULL,
    name           TEXT NOT NULL,
    purpose        TEXT,                            -- the one-line summary under the title
    help_page_id   INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (script_step_id, locale)
);

CREATE TABLE script_step_sections (
    script_step_id INTEGER NOT NULL REFERENCES script_steps (id),
    locale         TEXT NOT NULL,
    position       INTEGER NOT NULL,                -- order on the page; keys can repeat (several examples)
    section_key    TEXT NOT NULL,                   -- from the heading's CSS class, e.g. 'ref-desc'
    heading        TEXT NOT NULL,
    body_text      TEXT NOT NULL,
    PRIMARY KEY (script_step_id, locale, position)
);

CREATE TABLE step_examples (
    id             INTEGER PRIMARY KEY,
    script_step_id INTEGER NOT NULL REFERENCES script_steps (id),
    locale         TEXT NOT NULL,
    position       INTEGER NOT NULL,
    title          TEXT,
    description    TEXT,
    body           TEXT NOT NULL,
    UNIQUE (script_step_id, locale, position)
);

CREATE TABLE step_compatibility (
    script_step_id INTEGER NOT NULL REFERENCES script_steps (id),
    product        TEXT NOT NULL,                   -- 'Pro', 'Go', 'WebD', 'Server', ... (help's own keys)
    supported      TEXT NOT NULL,                   -- 'Yes' | 'No' | 'Partial' (help's own values)
    PRIMARY KEY (script_step_id, product)
);

CREATE TABLE function_categories (
    id       INTEGER PRIMARY KEY,
    slug     TEXT NOT NULL UNIQUE,                  -- help URL basename: 'text-functions', 'json-functions-category'
    key      TEXT NOT NULL UNIQUE,                  -- export key: 'text', 'json', 'get'
    position INTEGER NOT NULL                       -- order on the help site
);

CREATE TABLE function_category_localizations (
    category_id  INTEGER NOT NULL REFERENCES function_categories (id),
    locale       TEXT NOT NULL,
    name         TEXT NOT NULL,                     -- 'Text functions'
    help_page_id INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (category_id, locale)
);

CREATE TABLE functions (
    id                       INTEGER PRIMARY KEY,
    slug                     TEXT UNIQUE,           -- help URL basename; NULL for curated-only entries (Get)
    name                     TEXT NOT NULL UNIQUE,  -- exactly as typed in a calculation: 'JSONSetElement'
    category_id              INTEGER REFERENCES function_categories (id),
    return_type              TEXT,                  -- export dataType: 'text', 'number', 'any', ...
    return_type_raw          TEXT,                  -- help wording: 'text, number, date, time, timestamp, container'
    signature                TEXT NOT NULL,         -- help's Format line verbatim
    min_args                 INTEGER,
    max_args                 INTEGER,               -- NULL = unlimited (or not parsed; see signature_status)
    signature_status         TEXT NOT NULL,         -- 'parsed' | 'needs-review' | 'curated'
    signature_issues         TEXT,                  -- why the parser was not confident, '; '-separated
    originated_in_version_id INTEGER REFERENCES fm_versions (id),
    originated_in_raw        TEXT,
    deprecated_in_version_id INTEGER REFERENCES fm_versions (id),
    removed_in_version_id    INTEGER REFERENCES fm_versions (id)
);

CREATE TABLE function_localizations (
    function_id  INTEGER NOT NULL REFERENCES functions (id),
    locale       TEXT NOT NULL,
    purpose      TEXT,                              -- help's one-line summary (Claris text: never exported)
    summary      TEXT,                              -- our own short wording, exported (<= 300 chars)
    help_page_id INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (function_id, locale)
);

CREATE TABLE function_parameters (
    id                INTEGER PRIMARY KEY,
    function_id       INTEGER NOT NULL REFERENCES functions (id),
    position          INTEGER NOT NULL,
    name              TEXT NOT NULL,                -- 'numberOfCharacters'; numbering stripped ('test1' -> 'test')
    type              TEXT NOT NULL,                -- export dataType
    type_source       TEXT NOT NULL,                -- 'inferred' (from the help description) | 'curated'
    optional          INTEGER NOT NULL,             -- 0/1
    repeatable        INTEGER NOT NULL,             -- 0/1
    group_key         TEXT,                         -- parameters sharing a group repeat together
    help_description  TEXT,                         -- help wording (never exported)
    UNIQUE (function_id, position)
);

CREATE TABLE function_compatibility (
    function_id INTEGER NOT NULL REFERENCES functions (id),
    product     TEXT NOT NULL,                      -- help's own keys, as in step_compatibility
    supported   TEXT NOT NULL,                      -- 'Yes' | 'No' | 'Partial'
    PRIMARY KEY (function_id, product)
);

CREATE TABLE function_verifications (
    function_id   INTEGER NOT NULL REFERENCES functions (id),
    fm_version_id INTEGER NOT NULL REFERENCES fm_versions (id),
    arg_count     INTEGER NOT NULL,
    is_valid      INTEGER NOT NULL,                 -- IsValidExpression result, 0/1
    observed_at   TEXT NOT NULL,
    PRIMARY KEY (function_id, fm_version_id, arg_count)
);

CREATE TABLE get_constants (
    id                       INTEGER PRIMARY KEY,
    slug                     TEXT NOT NULL UNIQUE,  -- 'get-accountname'
    name                     TEXT NOT NULL UNIQUE,
    return_type              TEXT,
    return_type_raw          TEXT,
    originated_in_version_id INTEGER REFERENCES fm_versions (id),
    originated_in_raw        TEXT,
    deprecated_in_version_id INTEGER REFERENCES fm_versions (id),
    removed_in_version_id    INTEGER REFERENCES fm_versions (id)
);

CREATE TABLE get_constant_localizations (
    get_constant_id INTEGER NOT NULL REFERENCES get_constants (id),
    locale          TEXT NOT NULL,
    purpose         TEXT,
    summary         TEXT,
    help_page_id    INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (get_constant_id, locale)
);

CREATE TABLE get_constant_compatibility (
    get_constant_id INTEGER NOT NULL REFERENCES get_constants (id),
    product         TEXT NOT NULL,
    supported       TEXT NOT NULL,
    PRIMARY KEY (get_constant_id, product)
);

CREATE TABLE calc_help_sections (
    help_page_id INTEGER NOT NULL REFERENCES help_pages (id),
    position     INTEGER NOT NULL,
    section_key  TEXT NOT NULL,                     -- 'ref-format', 'ref-param', 'ref-desc', ...
    heading      TEXT NOT NULL,
    body_text    TEXT NOT NULL,
    PRIMARY KEY (help_page_id, position)
);

CREATE TABLE calc_constants (
    id                       INTEGER PRIMARY KEY,
    name                     TEXT NOT NULL UNIQUE,
    group_key                TEXT NOT NULL,         -- 'boolean', 'json-type', 'text-style'
    group_raw                TEXT,                  -- help's Category column
    value_json               TEXT,                  -- curated: '1', '"x"', NULL when not a plain value
    help_notes               TEXT,                  -- help's Notes column (never exported)
    originated_in_version_id INTEGER REFERENCES fm_versions (id),
    help_page_id             INTEGER REFERENCES help_pages (id),
    help_url                 TEXT                   -- curated link (e.g. the function page that uses it)
);

CREATE TABLE function_parameter_constants (
    parameter_id INTEGER NOT NULL REFERENCES function_parameters (id),
    constant_id  INTEGER NOT NULL REFERENCES calc_constants (id),
    PRIMARY KEY (parameter_id, constant_id)
);

CREATE TABLE calc_operators (
    id            INTEGER PRIMARY KEY,
    symbol        TEXT NOT NULL UNIQUE,             -- primary spelling: '≠'
    alternates    TEXT NOT NULL DEFAULT '[]',       -- JSON array: '["<>"]'
    name          TEXT NOT NULL,
    kind          TEXT NOT NULL,                    -- 'arithmetic' | 'text' | 'comparison' | 'logical' | ...
    arity         INTEGER NOT NULL,
    precedence    INTEGER NOT NULL,                 -- higher binds tighter
    associativity TEXT NOT NULL,                    -- 'left' | 'right' | 'none'
    help_url      TEXT
);

CREATE TABLE calc_syntax_rules (
    key        TEXT PRIMARY KEY,                    -- 'argumentSeparator', 'stringEscapes', ...
    value_json TEXT NOT NULL
);

CREATE TABLE error_codes (
    code                     INTEGER PRIMARY KEY,
    help_text                TEXT,                  -- help's description (Claris text: never exported)
    label                    TEXT,                  -- our own short label, exported when set
    originated_in_version_id INTEGER REFERENCES fm_versions (id),
    help_page_id             INTEGER REFERENCES help_pages (id)
);

CREATE TABLE sources (
    id            INTEGER PRIMARY KEY,
    kind          TEXT NOT NULL,                    -- 'clipboard_export' | 'saxml_export' | 'ddr_export' | 'pdf_printout' | 'manual'
    fm_version_id INTEGER REFERENCES fm_versions (id),
    uri_or_path   TEXT NOT NULL,                    -- repo-relative file or URL
    captured_at   TEXT,                             -- ISO 8601; when the export was made, if known
    sha256        TEXT,                             -- of the file
    notes         TEXT,
    UNIQUE (kind, uri_or_path, sha256)
);

CREATE TABLE step_options (
    id                       INTEGER PRIMARY KEY,
    script_step_id           INTEGER NOT NULL REFERENCES script_steps (id),
    key                      TEXT NOT NULL,         -- 'skip_data_entry_validation'
    value_type               TEXT NOT NULL,         -- 'boolean' | 'enum' | 'calculation' | 'text' | 'field' | 'script' | 'layout' | 'number' | ...
    required                 INTEGER NOT NULL DEFAULT 0,
    default_value            TEXT,
    position                 INTEGER NOT NULL,      -- order on the help page
    introduced_in_version_id INTEGER REFERENCES fm_versions (id), origin TEXT NOT NULL DEFAULT 'curated',
    UNIQUE (script_step_id, key)
);

CREATE TABLE step_option_localizations (
    step_option_id INTEGER NOT NULL REFERENCES step_options (id),
    locale         TEXT NOT NULL,
    label          TEXT NOT NULL,
    description    TEXT,
    help_page_id   INTEGER REFERENCES help_pages (id),
    PRIMARY KEY (step_option_id, locale)
);

CREATE TABLE step_option_values (
    id             INTEGER PRIMARY KEY,
    step_option_id INTEGER NOT NULL REFERENCES step_options (id),
    value          TEXT NOT NULL,                   -- language-neutral key, usually the XML value: 'OriginalLayout'
    position       INTEGER NOT NULL,
    UNIQUE (step_option_id, value)
);

CREATE TABLE step_option_value_localizations (
    step_option_value_id INTEGER NOT NULL REFERENCES step_option_values (id),
    locale               TEXT NOT NULL,
    label                TEXT NOT NULL,             -- 'original layout'
    PRIMARY KEY (step_option_value_id, locale)
);

CREATE TABLE step_configurations (
    id              INTEGER PRIMARY KEY,
    script_step_id  INTEGER NOT NULL REFERENCES script_steps (id),
    key             TEXT NOT NULL,                  -- 'default', 'with-target-field', ...
    description     TEXT,
    is_baseline     INTEGER NOT NULL DEFAULT 0,
    setting_summary TEXT,                           -- JSON {option_key: value}
    location        TEXT,                           -- script name + step index in the sample file
    UNIQUE (script_step_id, key)
);

CREATE UNIQUE INDEX idx_step_configurations_baseline ON step_configurations (script_step_id) WHERE is_baseline = 1;

CREATE TABLE clipboard_xml_representations (
    id               INTEGER PRIMARY KEY,
    script_step_id   INTEGER NOT NULL REFERENCES script_steps (id),
    configuration_id INTEGER REFERENCES step_configurations (id),
    shape_hash       TEXT NOT NULL,                 -- of the normalized element/attribute structure, not values
    example_xml      TEXT NOT NULL,                 -- a verbatim snippet of this shape
    notes            TEXT
);

CREATE UNIQUE INDEX idx_clipboard_xml_representations_shape
    ON clipboard_xml_representations (script_step_id, IFNULL(configuration_id, 0), shape_hash);

CREATE TABLE clipboard_xml_elements (
    id                INTEGER PRIMARY KEY,
    representation_id INTEGER NOT NULL REFERENCES clipboard_xml_representations (id),
    step_option_id    INTEGER REFERENCES step_options (id),  -- NULL for structural or not-yet-mapped leaves
    xml_path          TEXT NOT NULL,                -- index-free: 'NewWndStyles/@Close', 'TargetFields/Field/@map'
    parent_path       TEXT,                         -- the containing element: 'NewWndStyles', 'TargetFields/Field'
    repeat_index      INTEGER NOT NULL DEFAULT 0,   -- 0-based among siblings of the innermost repeating element
    value_type        TEXT,
    allowed_values    TEXT,                         -- JSON array
    default_value     TEXT,
    example_value     TEXT,                         -- value in example_xml
    always_present    INTEGER,                      -- 0/1/NULL (unknown until two configurations are compared)
    position          INTEGER NOT NULL,             -- document order within the step
    UNIQUE (representation_id, xml_path, repeat_index)
);

CREATE INDEX idx_clipboard_xml_elements_option ON clipboard_xml_elements (step_option_id);

CREATE TABLE clipboard_xml_observations (
    representation_id INTEGER NOT NULL REFERENCES clipboard_xml_representations (id),
    source_id         INTEGER NOT NULL REFERENCES sources (id),
    PRIMARY KEY (representation_id, source_id)
);

CREATE TABLE ui_representations (
    id               INTEGER PRIMARY KEY,
    script_step_id   INTEGER NOT NULL REFERENCES script_steps (id),
    configuration_id INTEGER REFERENCES step_configurations (id),
    locale           TEXT NOT NULL,
    shape_hash       TEXT NOT NULL,                 -- of display template + option layout
    display_name     TEXT,                          -- when the editor shows a different name than the step's
    display_template TEXT,                          -- 'Commit Records/Requests [ {noInteract} ; ... ]'
    example_text     TEXT                           -- a real line captured from a printout
);

CREATE UNIQUE INDEX idx_ui_representations_shape
    ON ui_representations (script_step_id, IFNULL(configuration_id, 0), locale, shape_hash);

CREATE TABLE ui_options (
    id                   INTEGER PRIMARY KEY,
    ui_representation_id INTEGER NOT NULL REFERENCES ui_representations (id),
    step_option_id       INTEGER REFERENCES step_options (id),
    label                TEXT,
    display_location     TEXT NOT NULL,             -- 'inline' | 'continuation' | 'dialog_only'
    position             INTEGER NOT NULL,          -- order within the line
    repeat_index         INTEGER NOT NULL DEFAULT 0,
    omit_when_false      INTEGER,
    true_text            TEXT,
    false_text           TEXT,
    example_text         TEXT,                      -- the segment as printed: 'Close:Yes'
    UNIQUE (ui_representation_id, position, repeat_index)
);

CREATE INDEX idx_ui_options_option ON ui_options (step_option_id);

CREATE TABLE ui_option_value_displays (
    ui_option_id INTEGER NOT NULL REFERENCES ui_options (id),
    value        TEXT NOT NULL,                     -- XML value: 'ResizeToFit'
    display_text TEXT NOT NULL,                     -- printed text: 'Resize to Fit'
    PRIMARY KEY (ui_option_id, value)
);

CREATE TABLE ui_observations (
    ui_representation_id INTEGER NOT NULL REFERENCES ui_representations (id),
    source_id            INTEGER NOT NULL REFERENCES sources (id),
    PRIMARY KEY (ui_representation_id, source_id)
);

CREATE VIEW current_clipboard_xml_representations AS
SELECT id, script_step_id, configuration_id, shape_hash, example_xml, notes, observed_version
FROM (
    SELECT r.*, v.version AS observed_version,
           ROW_NUMBER() OVER (PARTITION BY r.script_step_id, IFNULL(r.configuration_id, 0)
                              ORDER BY v.sort_key DESC, r.id DESC) AS rn
    FROM clipboard_xml_representations r
    JOIN clipboard_xml_observations o ON o.representation_id = r.id
    JOIN sources s ON s.id = o.source_id
    JOIN fm_versions v ON v.id = s.fm_version_id
)
WHERE rn = 1;

CREATE VIEW current_ui_representations AS
SELECT id, script_step_id, configuration_id, locale, shape_hash, display_name, display_template, example_text,
       observed_version
FROM (
    SELECT r.*, v.version AS observed_version,
           ROW_NUMBER() OVER (PARTITION BY r.script_step_id, IFNULL(r.configuration_id, 0), r.locale
                              ORDER BY v.sort_key DESC, r.id DESC) AS rn
    FROM ui_representations r
    JOIN ui_observations o ON o.ui_representation_id = r.id
    JOIN sources s ON s.id = o.source_id
    JOIN fm_versions v ON v.id = s.fm_version_id
)
WHERE rn = 1;
