-- calc_syntax_rules: generated by `catalogue_db.py dump`; change the database, not this file.
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('argumentSeparator', '";"');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('blockComment', '["/*", "*/"]');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('caseSensitive', '{"functionNames": false}');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('fieldReference', '"Table::Field"');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('lineComment', '"//"');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('notes', '["Operator precedence follows help.claris.com/en/pro-help/content/operators-in-formulas.html (higher number binds tighter).", "${ } quotes reserved function names and keywords used as field or table names (text-operators.html)."]');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('paragraphMark', '"¶"');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('repetitionBrackets', '["[", "]"]');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('stringDelimiter', '"\""');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('stringEscapes', '[{"sequence": "\\\"", "meaning": "a quotation mark inside a text constant"}, {"sequence": "\\\\", "meaning": "a backslash inside a text constant"}, {"sequence": "\\¶", "meaning": "a literal pilcrow instead of a return"}]');
INSERT INTO "calc_syntax_rules" ("key", "value_json") VALUES ('variablePrefixes', '[{"prefix": "$$", "scope": "file (global)"}, {"prefix": "$", "scope": "script (local)"}]');
