-- script_step_categories: generated by `catalogue_db.py dump`; change the database, not this file.
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (1, 'control', 0);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (2, 'navigation', 1);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (3, 'editing', 2);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (4, 'fields', 3);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (5, 'records', 4);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (6, 'found-sets', 5);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (7, 'windows', 6);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (8, 'files', 7);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (9, 'accounts', 8);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (10, 'artificial-intelligence', 9);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (11, 'spelling', 10);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (12, 'pdf-files', 11);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (13, 'open-menu-item', 12);
INSERT INTO "script_step_categories" ("id", "slug", "position") VALUES (14, 'miscellaneous', 13);
